name: Test

on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  db_name: testlogstreams
  db_user: testlogstreams
  db_pass: testlogstreams123

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mariadb:10.11.6
        env:
          MYSQL_DATABASE: ${{ env.db_name }}
          MYSQL_USER: ${{ env.db_user }}
          MYSQL_PASSWORD: ${{ env.db_pass }}
          MYSQL_ROOT_PASSWORD: ${{ env.db_pass }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        env:
          DB_PASS: ${{ env.db_pass }}
        run: sbt +test
