name: Test

on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_DATABASE: testlogstreams
          MYSQL_USER: testlogstreams
          MYSQL_PASSWORD: testlogstreams123
          MYSQL_ROOT_PASSWORD: testlogstreams123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        env:
          DB_PASS: testlogstreams123
        run: sbt +test
