package com.malliina.logstreams.models

case class DayViewHeaderFormat(month: String, year: String)

case class DateFormats(
  LTS: String,
  LT: String,
  L: String,
  LL: String,
  LLL: String,
  LLLL: String
)

case class TimeLang(
  today: String,
  clear: String,
  close: String,
  selectMonth: String,
  previousMonth: String,
  nextMonth: String,
  selectYear: String,
  previousYear: String,
  nextYear: String,
  selectDecade: String,
  previousDecade: String,
  nextDecade: String,
  previousCentury: String,
  nextCentury: String,
  pickHour: String,
  incrementHour: String,
  decrementHour: String,
  pickMinute: String,
  incrementMinute: String,
  decrementMinute: String,
  pickSecond: String,
  incrementSecond: String,
  decrementSecond: String,
  toggleMeridiem: String,
  selectTime: String,
  selectDate: String,
  dayViewHeaderFormat: DayViewHeaderFormat,
  locale: String,
  startOfTheWeek: Int,
  hourCycle: String,
  dateFormats: DateFormats,
//ordinal: (n) => n,
  format: String,
  toggleAriaLabel: String
)

object TimeLang:
  val en = TimeLang(
    "Go to today",
    "Clear selection",
    "Close the picker",
    "Select Month",
    "Previous Month",
    "Next Month",
    "Select Year",
    "Previous Year",
    "Next Year",
    "Select Decade",
    "Previous Decade",
    "Next Decade",
    "Previous Century",
    "Next Century",
    "Pick Hour",
    "Increment Hour",
    "Decrement Hour",
    "Pick Minute",
    "Increment Minute",
    "Decrement Minute",
    "Pick Second",
    "Increment Second",
    "Decrement Second",
    "Toggle Meridiem",
    "Select Time",
    "Select Date",
    DayViewHeaderFormat("long", "2-digit"),
    "default",
    0,
    "",
    DateFormats(
      "h:mm:ss T",
      "h:mm T",
      "MM/dd/yyyy",
      "MMMM d, yyyy",
      "MMMM d, yyyy h:mm T",
      "dddd, MMMM d, yyyy h:mm T"
    ),
    "L",
    "Change date"
  )
  val se = TimeLang(
    "Gå till idag",
    "Rensa",
    "Stäng",
    "Välj månad",
    "Föregående månad",
    "Följande månad",
    "Välj år",
    "Föregående år",
    "Följande år",
    "Välj decennium",
    "Föregående decennium",
    "Följande decennium",
    "Föregående århundrade",
    "Följande århundrade",
    "Välj timme",
    "Öka timme",
    "Reducera timme",
    "Välj minut",
    "Öka minut",
    "Reducera minut",
    "Välj sekund",
    "Öka sekund",
    "Reducera sekund",
    "Välj meridium",
    "Välj tid",
    "Välj datum",
    DayViewHeaderFormat("long", "2-digit"),
    "default",
    0,
    "",
    DateFormats(
      "h:mm:ss T",
      "h:mm T",
      "MM/dd/yyyy",
      "MMMM d, yyyy",
      "MMMM d, yyyy h:mm T",
      "dddd, MMMM d, yyyy h:mm T"
    ),
    "L",
    "Ändra datum"
  )
